language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
addons:
  sauce_connect: true
    username: "testyantra1"
    access_key: "f81a366e-8252-4af4-a850-9cf37d3bc9e2"
caps = Selenium::WebDriver::Remote::Capabilities.firefox({
  'tunnel-identifier' => ENV['TRAVIS_JOB_NUMBER']
})
driver = Selenium::WebDriver.for(:remote, {
  url: 'http://testyantra1:f81a366e-8252-4af4-a850-9cf37d3bc9e2@ondemand.saucelabs.com/wd/hub',
  desired_capabilities: caps
})
